export class Place{
    public id: number;
    public name: string;
    public description: string;
    public country: string;
    public images: Array<any>[];
    public img_url1: string;
    public img_url2: string;
    public img_url3: string;
    public img_url4: string;
    public img_url5: string;
    public img_url6: string;
    public img_url7: string;
    public img_url8: string;
    public img_url9: string;
    public img_url10: string;
    public latitude: string;
    public longitude: string;
}